version: '3.8'

services:
  app:
    image: karamontoure26/node-express-cicd:latest
    ports:
      - "3000:3000"
    container_name: node-app
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    restart: unless-stopped
